# Generated by Django 5.2.7 on 2025-10-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('topic_name', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=50)),
                ('order', models.IntegerField()),
            ],
        ),
    ]
