# Generated by Django 5.2.5 on 2026-01-06 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id_num', models.IntegerField(primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Infosis_WD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=100)),
                ('topic1', models.CharField(max_length=100)),
                ('topic2', models.CharField(max_length=100)),
                ('topic3', models.CharField(max_length=100)),
                ('topic4', models.CharField(max_length=100)),
                ('info_wd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prep.selection')),
            ],
        ),
    ]
