# Generated by Django 5.2.5 on 2026-01-11 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosis_wd',
            name='info_wd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infosis_wd', to='prep.selection'),
        ),
        migrations.CreateModel(
            name='TCS_WD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=100)),
                ('topic1', models.CharField(max_length=100)),
                ('topic2', models.CharField(max_length=100)),
                ('topic3', models.CharField(max_length=100)),
                ('topic4', models.CharField(max_length=100)),
                ('topic5', models.CharField(max_length=100)),
                ('tcs_wd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tcs_wd', to='prep.selection')),
            ],
        ),
    ]
