# Generated by Django 5.2.5 on 2026-01-11 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep', '0002_alter_infosis_wd_info_wd_tcs_wd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wipro_WD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=100)),
                ('topic1', models.CharField(max_length=100)),
                ('topic2', models.CharField(max_length=100)),
                ('topic3', models.CharField(max_length=100)),
                ('topic4', models.CharField(max_length=100)),
                ('wipro_wd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wipro_wd', to='prep.selection')),
            ],
        ),
    ]
