# Generated by Django 6.0 on 2026-02-25 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep', '0003_wipro_wd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcs_wd',
            name='tcs_wd',
        ),
        migrations.RemoveField(
            model_name='wipro_wd',
            name='wipro_wd',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('college_name', models.CharField(blank=True, max_length=255)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('target_domain', models.CharField(blank=True, max_length=100)),
                ('target_company', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('last_login_date', models.DateField(blank=True, null=True)),
                ('current_streak', models.IntegerField(default=0)),
                ('max_streak', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Infosis_WD',
        ),
        migrations.DeleteModel(
            name='TCS_WD',
        ),
        migrations.DeleteModel(
            name='Selection',
        ),
        migrations.DeleteModel(
            name='Wipro_WD',
        ),
    ]
