# Generated by Django 6.0 on 2026-02-25 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep', '0006_placementprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('question_type', models.CharField(choices=[('aptitude', 'Aptitude'), ('coding', 'Coding'), ('interview', 'Interview')], max_length=20)),
                ('page_number', models.IntegerField(default=1)),
                ('question_text', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('leetcode_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
